CREATE PROCEDURE CONIPISOS.INSERTAR_FOTO
@ARTICULO VARCHAR(50),
@SECUENCIA VARCHAR(50),
@FOTO IMAGE,
@PRIORIDAD VARCHAR(50),
@ARCHIVO VARCHAR(50),
@DESCRIPCION VARCHAR(50),
@FECHA datetime
AS

INSERT INTO CONIPISOS.ARTICULO_FOTO (ARTICULO,SECUENCIA,FOTO,PRIORIDAD,ARCHIVO,DESCRIPCION,FECHA_ULT_MODIF) VALUES(@ARTICULO,@SECUENCIA,@FOTO,@PRIORIDAD,@ARCHIVO,@DESCRIPCION,@FECHA) 
